### ISSUE TITLE
Q: does embeded schema supported? 

### ISSUE THREAD

**Issue by chichunhua** [hamba/avro#147]
I wrote in separate avsc file. when I embed the last one event to marshal it, got errors `"unknown type: "`. Does embeded schema supported in hamba? Not sure if I missed something else. Looking forward your kind reply, Thanks!
```
{
  "type": "enum",
  "name": "status",
  "namespace": "xxx"
  "symbols": [
    "on",
    "off"
  ]
}
{
  "type": "record",
  "name": "payload",
  "version": "1",
  "namespace": "xxx"
  "fields": [
    {
      "name": "id",
      "type": "string",
    },
    {
      "name": "status",
      "type": "xxx.status",
    }
  ]
}
{
  "type": "record",
  "name": "event",
  "version": "1",
  "namespace": "xxxi"
  "fields": [
    {
      "name": "time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
    },
    {
      "name": "type",
      "type": "string",
    },
    {
      "name": "data",
      "type": "xxx.payload"
    }
  ]
}
```

**Comment by nrwiersma** [comment]
Hi,

Yes, it should be supported. Can you provide a code snippet of what you are doing, how you are parsing the schema and marshalling?

**Comment by chichunhua** [comment]
```
package main

import (
	_ "embed"
	"fmt"
	"github.com/hamba/avro"
	"log"
	"time"
)

//go:embed api/event.avsc
var eventSchemaStr string

//go:embed api/payload.avsc
var payloadSchemaStr string

//go:embed api/status.avsc
var statusSchemaStr string

type status int

const (
	on  = 0
	off = 1
)

type Payload struct {
	Id     string `avro:"node_id"`
	Status status `avro:"status"`
}

type Event struct {
	Time time.Time `avro:"time"`
	Data Payload   `avro:"data"`
}

func main() {
	statusSchem, err := avro.Parse(statusSchemaStr)
	if err != nil {
		log.Fatal(err)
	}
	payloadSchem, err := avro.Parse(payloadSchemaStr)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("%T, %T", statusSchem, payloadSchem)

	eventSchem, err := avro.Parse(eventSchemaStr)
	if err != nil {
		log.Fatal(err)
	}

	e := Event{
		Time: time.Now(),
		Data: Payload{
			Id:     "2CC407",
			Status: 0,
		},
	}

	b, err := avro.Marshal(eventSchem, e)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Print(b)
}

```

**Comment by nrwiersma** [comment]
Ok, it works fine once you remove the errors in your schema, add the required `type` in payload and make `Status` a string (as it is an enum, it must be a string). So the following works for me on the latest version:

```yaml
{
  "type": "enum",
  "name": "status",
  "namespace": "xxx",
  "symbols": [
    "on",
    "off"
  ]
}
```
```yaml
{
  "type": "record",
  "name": "payload",
  "version": "1",
  "namespace": "xxx",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "status",
      "type": "xxx.status"
    }
  ]
}
```
```yaml
{
  "type": "record",
  "name": "event",
  "version": "1",
  "namespace": "xxxi",
  "fields": [
    {
      "name": "time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "type",
      "type": "string"
    },
    {
      "name": "data",
      "type": "xxx.payload"
    }
  ]
}
```
```go
package main

import (
	_ "embed"
	"fmt"
	"log"
	"time"

	"github.com/hamba/avro"
)

//go:embed event.avsc
var eventSchemaStr string

//go:embed payload.avsc
var payloadSchemaStr string

//go:embed status.avsc
var statusSchemaStr string

type status string

type Payload struct {
	Id     string `avro:"id"`
	Status status `avro:"status"`
}

type Event struct {
	Time time.Time `avro:"time"`
	Type string    `avro:"type"`
	Data Payload   `avro:"data"`
}

func main() {
	statusSchem, err := avro.Parse(statusSchemaStr)
	if err != nil {
		log.Fatal("Parse Status ", err)
	}
	payloadSchem, err := avro.Parse(payloadSchemaStr)
	if err != nil {
		log.Fatal("Parse Payload ", err)
	}
	fmt.Println("%T, %T", statusSchem, payloadSchem)

	eventSchem, err := avro.Parse(eventSchemaStr)
	if err != nil {
		log.Fatal("Parse Event ", err)
	}

	e := Event{
		Time: time.Now(),
		Type: "SomeType",
		Data: Payload{
			Id:     "2CC407",
			Status: "on",
		},
	}

	b, err := avro.Marshal(eventSchem, e)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Print(b)
}
```
