### ISSUE TITLE
Keep a detailed version of schema in case of generation with encoders flag

### ISSUE THREAD

**Issue by vdorokhin** [hamba/avro#441]
Currently (v2.25.1) schema from generated struct with encoders flag is hardly useful to work with confluent schema registry. This includes verifying that the schema is present, retrieving its ID, and retaining context when registering a schema based on the generated structure. In the current implementation, the String() method is used when building the context for structure generation via a template. This approach results without fields like doc, default, etc.
This leads to an issue where the attempt to determine if the schema is present in the registry and to retrieve its ID fails, as the schema is not found.

The issue can be reproduced using the following steps:
#### 1. Generate structs by schema versions
```go
package main

import (
	"bytes"
	"go/format"
	"os"

	"github.com/hamba/avro/v2"
	"github.com/hamba/avro/v2/gen"
)

const (
	generatedDirPath      = "./generated"
	firstVersionOfSchema  = `{"type":"record","name":"test","namespace":"a.b","doc":"Test is a test struct","fields":[{"name":"someString","type":"string","doc":"SomeString is a string"}]}`
	secondVersionOfSchema = `{"type":"record","name":"test","namespace":"a.b","doc":"Test is a test struct","fields":[{"name":"someString","type":"string","doc":"SomeString is a string"},{"name":"someOptionalInt","type":["null","int"],"default":null,"doc":"SomeOptionalInt is an optional int"}]}`
)

func main() {
	generateStruct("v1", firstVersionOfSchema)
	generateStruct("v2", secondVersionOfSchema)
}

func generateStruct(pkg string, schema string) {
	generatedDir := generatedDirPath + "/" + pkg
	if err := os.MkdirAll(generatedDir, 0755); os.IsExist(err) {
		if os.IsExist(err) {
			noError(os.RemoveAll(generatedDir))
		} else {
			noError(err)
		}
	}

	g := gen.NewGenerator(pkg, map[string]gen.TagStyle{}, gen.WithEncoders(true))
	g.Parse(avro.MustParse(schema))

	buf := new(bytes.Buffer)
	noError(g.Write(buf))

	formatted, err := format.Source(buf.Bytes())
	noError(err)

	noError(os.WriteFile(generatedDir+"/struct.go", formatted, 0600))
}

func noError(err error) {
	if err != nil {
		panic(err)
	}
}
```
First version of schema:
```avro
{
  "type": "record",
  "name": "test",
  "namespace": "a.b",
  "doc": "Test is a test struct",
  "fields": [
    {
      "name": "someString",
      "type": "string",
      "doc": "SomeString is a string"
    }
  ]
}
```
Second version of schema:
```avro
{
  "type": "record",
  "name": "test",
  "namespace": "a.b",
  "doc": "Test is a test struct",
  "fields": [
    {
      "name": "someString",
      "type": "string",
      "doc": "SomeString is a string"
    },
    {
      "name": "someOptionalInt",
      "type": [
        "null",
        "int"
      ],
      "default": null,
      "doc": "SomeOptionalInt is an optional int"
    }
  ]
}
```
Generated structs in current version of lib:
v1:
```go
package v1

// Code generated by avro/gen. DO NOT EDIT.

import (
	"github.com/hamba/avro/v2"
)

// Test is a test struct.
type Test struct {
	// SomeString is a string.
	SomeString string `avro:"someString"`
}

var schemaTest = avro.MustParse(`{"name":"a.b.test","type":"record","fields":[{"name":"someString","type":"string"}]}`)

// Schema returns the schema for Test.
func (o *Test) Schema() avro.Schema {
	return schemaTest
}

// Unmarshal decodes b into the receiver.
func (o *Test) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Test) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}

```
v2:
```go
package v2

// Code generated by avro/gen. DO NOT EDIT.

import (
	"github.com/hamba/avro/v2"
)

// Test is a test struct.
type Test struct {
	// SomeString is a string.
	SomeString string `avro:"someString"`
	// SomeOptionalInt is an optional int.
	SomeOptionalInt *int `avro:"someOptionalInt"`
}

var schemaTest = avro.MustParse(`{"name":"a.b.test","type":"record","fields":[{"name":"someString","type":"string"},{"name":"someOptionalInt","type":["null","int"]}]}`)

// Schema returns the schema for Test.
func (o *Test) Schema() avro.Schema {
	return schemaTest
}

// Unmarshal decodes b into the receiver.
func (o *Test) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Test) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
```
#### 2. Run following code...
```go
package main

import (
	"context"
	"errors"
	"fmt"

	"github.com/hamba/avro/v2"
	v1 "github.com/hamba/avro/v2/generated/v1"
	v2 "github.com/hamba/avro/v2/generated/v2"
	"github.com/hamba/avro/v2/registry"
)

const (
	registryURL = "http://localhost:8081"
	subjectName = `a.b.test`
	firstVersionOfSchema  = `{"type":"record","name":"test","namespace":"a.b","doc":"Test is a test struct","fields":[{"name":"someString","type":"string","doc":"SomeString is a string"}]}`
	secondVersionOfSchema = `{"type":"record","name":"test","namespace":"a.b","doc":"Test is a test struct","fields":[{"name":"someString","type":"string","doc":"SomeString is a string"},{"name":"someOptionalInt","type":["null","int"],"default":null,"doc":"SomeOptionalInt is an optional int"}]}`
)

func main() {
	ctx := context.Background()

	reg, err := registry.NewClient(registryURL)
	noError(err)

	firstVersionID, _, err := reg.CreateSchema(ctx, subjectName, firstVersionOfSchema)
	noError(err)

	secondVersionID, _, err := reg.CreateSchema(ctx, subjectName, secondVersionOfSchema)
	noError(err)

	if firstVersionID == secondVersionID {
		noError(errors.New("ids should be different"))
	}

	schemaID, _, err := reg.IsRegistered(ctx, subjectName, firstVersionOfSchema)
	noError(err)
	if firstVersionID != schemaID {
		noError(fmt.Errorf("expected schemaID %q, got %q", firstVersionID, schemaID))
	}

	schemaID, _, err = reg.IsRegistered(ctx, subjectName, secondVersionOfSchema)
	noError(err)
	if secondVersionID != schemaID {
		noError(fmt.Errorf("expected schemaID %q, got %q", secondVersionID, schemaID))
	}

	firstSchemaFromStruct := new(v1.Test).Schema().(*avro.RecordSchema)

	firstSchemaJSON, err := firstSchemaFromStruct.MarshalJSON()
	noError(err)

	schemaID, _, err = reg.IsRegistered(ctx, firstSchemaFromStruct.FullName(), string(firstSchemaJSON))
	noError(err)
	if firstVersionID != schemaID {
		noError(fmt.Errorf("expected schemaID %q, got %q", firstVersionID, schemaID))
	}

	secondSchemaFromStruct := new(v2.Test).Schema().(*avro.RecordSchema)

	secondSchemaJSON, err := secondSchemaFromStruct.MarshalJSON()
	noError(err)

	schemaID, _, err = reg.IsRegistered(ctx, secondSchemaFromStruct.FullName(), string(secondSchemaJSON))
	noError(err)
	if secondVersionID != schemaID {
		noError(fmt.Errorf("expected schemaID %q, got %q", firstVersionID, schemaID))
	}

	fmt.Println("All checks passed")
}

func noError(err error) {
	if err != nil {
		panic(err)
	}
}
```
This code requires a locally running schema registry. I used the following compose file for this purpose...
```yaml
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.6
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.4.6
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - '19092:19092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://localhost:19092
      SCHEMA_REGISTRY_DEBUG: 'true'
      SCHEMA_REGISTRY_LATEST_COMPATIBILITY_STRICT: 'false'

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    depends_on:
      - broker
    ports:
      - '8080:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
```
Actual result:
```log
panic: Schema not found io.confluent.rest.exceptions.RestNotFoundException: Schema not found
io.confluent.rest.exceptions.RestNotFoundException: Schema not found
        at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.schemaNotFoundException(Errors.java:121)
        at io.confluent.kafka.schemaregistry.rest.resources.SubjectsResource.lookUpSchemaUnderSubject(SubjectsResource.java:132)
        .....
        at java.base/java.lang.Thread.run(Thread.java:840)

goroutine 1 [running]:
main.noError(...)
        .../avro/test/main.go:71
main.main()
        .../avro/test/main.go:53 +0x63c (IsRegistered by firstSchemaJSON)

```

The simplest solution seems to be replacing the call to the String() method with the MarshalJSON() method during resolveRecordSchema. I’ve already tested it and made the following changes...
```go
func (g *Generator) resolveRecordSchema(schema *avro.RecordSchema) string {
	fields := make([]field, len(schema.Fields()))
	for i, f := range schema.Fields() {
		typ := g.generate(f.Type())
		fields[i] = g.newField(g.nameCaser.ToPascal(f.Name()), typ, f.Doc(), f.Name())
	}

	typeName := g.resolveTypeName(schema)
	if !g.hasTypeDef(typeName) {
		var rawSchema string
		if schemaJSON, err := schema.MarshalJSON(); err != nil {
                         // can print some WARN here or panic
			rawSchema = schema.String()
		} else {
			rawSchema = string(schemaJSON)
		}
		g.typedefs = append(g.typedefs, newType(typeName, schema.Doc(), fields, rawSchema))
	}
	return typeName
}
```
Structs after this changes...
v1:
```go
package v1

// Code generated by avro/gen. DO NOT EDIT.

import (
	"github.com/hamba/avro/v2"
)

// Test is a test struct.
type Test struct {
	// SomeString is a string.
	SomeString string `avro:"someString"`
}

var schemaTest = avro.MustParse(`{"name":"a.b.test","doc":"Test is a test struct","type":"record","fields":[{"name":"someString","doc":"SomeString is a string","type":"string"}]}`)

// Schema returns the schema for Test.
func (o *Test) Schema() avro.Schema {
	return schemaTest
}

// Unmarshal decodes b into the receiver.
func (o *Test) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Test) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
```
v2:
```go
package v2

// Code generated by avro/gen. DO NOT EDIT.

import (
	"github.com/hamba/avro/v2"
)

// Test is a test struct.
type Test struct {
	// SomeString is a string.
	SomeString string `avro:"someString"`
	// SomeOptionalInt is an optional int.
	SomeOptionalInt *int `avro:"someOptionalInt"`
}

var schemaTest = avro.MustParse(`{"name":"a.b.test","doc":"Test is a test struct","type":"record","fields":[{"name":"someString","doc":"SomeString is a string","type":"string"},{"name":"someOptionalInt","doc":"SomeOptionalInt is an optional int","type":["null","int"],"default":null}]}`)

// Schema returns the schema for Test.
func (o *Test) Schema() avro.Schema {
	return schemaTest
}

// Unmarshal decodes b into the receiver.
func (o *Test) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Test) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
```
After these changes, the verification code above completes successfully

In any case, I'm open to suggestions. There might be an opinion that this functionality should be hidden behind a flag, or perhaps there's another way to extract the original schema to pass it into the template. Let's discuss the options, and I'll create a PR with the changes
